# coding: utf-8

"""
    Selling Partner API for Catalog Items

    The Selling Partner API for Catalog Items helps you programmatically retrieve item details for items in the catalog.  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.number_of_offer_listings_list import NumberOfOfferListingsList  # noqa: E501
from swagger_client.rest import ApiException


class TestNumberOfOfferListingsList(unittest.TestCase):
    """NumberOfOfferListingsList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNumberOfOfferListingsList(self):
        """Test NumberOfOfferListingsList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.number_of_offer_listings_list.NumberOfOfferListingsList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
