# coding: utf-8

"""
    Selling Partner API for Catalog Items

    The Selling Partner API for Catalog Items helps you programmatically retrieve item details for items in the catalog.  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.sales_rank_type import SalesRankType  # noqa: E501
from swagger_client.rest import ApiException


class TestSalesRankType(unittest.TestCase):
    """SalesRankType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSalesRankType(self):
        """Test SalesRankType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.sales_rank_type.SalesRankType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
