# coding: utf-8

"""
    Selling Partner API for Catalog Items

    The Selling Partner API for Catalog Items helps you programmatically retrieve item details for items in the catalog.  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class DimensionType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'height': 'DecimalWithUnits',
        'length': 'DecimalWithUnits',
        'width': 'DecimalWithUnits',
        'weight': 'DecimalWithUnits'
    }

    attribute_map = {
        'height': 'Height',
        'length': 'Length',
        'width': 'Width',
        'weight': 'Weight'
    }

    def __init__(self, height=None, length=None, width=None, weight=None, _configuration=None):  # noqa: E501
        """DimensionType - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._height = None
        self._length = None
        self._width = None
        self._weight = None
        self.discriminator = None

        if height is not None:
            self.height = height
        if length is not None:
            self.length = length
        if width is not None:
            self.width = width
        if weight is not None:
            self.weight = weight

    @property
    def height(self):
        """Gets the height of this DimensionType.  # noqa: E501

        The height attribute of the dimension.  # noqa: E501

        :return: The height of this DimensionType.  # noqa: E501
        :rtype: DecimalWithUnits
        """
        return self._height

    @height.setter
    def height(self, height):
        """Sets the height of this DimensionType.

        The height attribute of the dimension.  # noqa: E501

        :param height: The height of this DimensionType.  # noqa: E501
        :type: DecimalWithUnits
        """

        self._height = height

    @property
    def length(self):
        """Gets the length of this DimensionType.  # noqa: E501

        The length attribute of the dimension.  # noqa: E501

        :return: The length of this DimensionType.  # noqa: E501
        :rtype: DecimalWithUnits
        """
        return self._length

    @length.setter
    def length(self, length):
        """Sets the length of this DimensionType.

        The length attribute of the dimension.  # noqa: E501

        :param length: The length of this DimensionType.  # noqa: E501
        :type: DecimalWithUnits
        """

        self._length = length

    @property
    def width(self):
        """Gets the width of this DimensionType.  # noqa: E501

        The width attribute of the dimension.  # noqa: E501

        :return: The width of this DimensionType.  # noqa: E501
        :rtype: DecimalWithUnits
        """
        return self._width

    @width.setter
    def width(self, width):
        """Sets the width of this DimensionType.

        The width attribute of the dimension.  # noqa: E501

        :param width: The width of this DimensionType.  # noqa: E501
        :type: DecimalWithUnits
        """

        self._width = width

    @property
    def weight(self):
        """Gets the weight of this DimensionType.  # noqa: E501

        The weight attribute of the dimension.  # noqa: E501

        :return: The weight of this DimensionType.  # noqa: E501
        :rtype: DecimalWithUnits
        """
        return self._weight

    @weight.setter
    def weight(self, weight):
        """Sets the weight of this DimensionType.

        The weight attribute of the dimension.  # noqa: E501

        :param weight: The weight of this DimensionType.  # noqa: E501
        :type: DecimalWithUnits
        """

        self._weight = weight

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DimensionType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DimensionType):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DimensionType):
            return True

        return self.to_dict() != other.to_dict()
